global:

campfire:
  subdomain: 'example'
  token: 'you@example.com'
  room_name: 1234
  ssl: true  

highrise:
 subdomain: 'example'
 # Find this in Highrise: My info -> User Account -> Reveal authentication token
 token: 'ABCDEF1234567890' 
